### ISSUE TITLE
Upload Files - No file explorer window

### ISSUE THREAD

**Issue by PhilJK** [weDevsOfficial/wp-project-manager#125]
Hi, 

Everything working on free plugin version in Wordpress 4.8.1, except when I start a discussion and attach files with "select files" from computer link. The page scrolls to top and no file dialog window or anything for me to select files.

What could be wrong?

Your help is appreciated.

**Comment by yeasin1989** [comment]
Hi, 

It seems like there is a theme layout issue. Would you please activate a default WordPress theme like as "TwentyTwelve" and check the issue again? I believe that it will work fine with a default WordPress theme because I have checked on my local server and on our demo- http://pmdemo.wedevs.com and found everything is working. 

After switching the theme if it is not working then please feel free to contact us.

Best regards :)

**Comment by PhilJK** [comment]
Hi

Thanks for responding.

I did activate TwentyTwelve and no change, the problem still exists. (Unfortunately, I didn’t realise that switching themes would destroy the footer widgets. Just spent two hours rebuilding!)

Obviously, I need to use my free version theme ‘Spacious by ThemeGrill’. Please could you try WP-Project-Manager with ‘Spacious’ (https://themegrill.com/themes/spacious/)?

Is there a debug routine that I could invoke? Would the error be logged anywhere?

Best regards
Philip
