### ISSUE TITLE
/wp-json/pm/v2/categories/index.html" is not found (2: No such file or directory)

### ISSUE THREAD

**Issue by tanzhenchao** [weDevsOfficial/wp-project-manager#305]
OS = Red Hat Enterprise Linux Server release 7.6 (Maipo)
Web Server Version = Nginx 1.14.0
PHP Version = 7.2.11
Wordpress Version = 4.9.9

`2019/07/11 16:39:10 [error] 18258#18258: *98 "/var/www/www.cmdschool.org/wp-json/pm/v2/categories/index.html" is not found (2: No such file or directory), client: 10.168.0.165, server: localhost, request: "GET /wp-json/pm/v2/categories/?per_page=-1&type=project&is_admin=1 HTTP/1.1", host: "www.cmdschool.org", referrer: "http://www.cmdschool.org/wp-admin/admin.php?page=pm_projects"`

**Comment by yeasin1989** [comment]
Hi @tanzhenchao,

Please do not worry, we will fix this issue.

It seems like you have missed update of the plugin on your site.
We have to check your site to reproduce the issue in that can please send a direct e-mail to support@wedevs.com so that our team can check your website and solve the problem for you :)

**Comment by tanzhenchao** [comment]
Thank you very much, I have not found the wp-json directory in my wwwroot. What causes files to go missing?
Inexplicably, below installation packages do not contain “w-json” directory.

https://wordpress.org/wordpress-4.9.9.tar.gz
https://downloads.wordpress.org/plugin/wedevs-project-manager.2.2.2.zip
